### ISSUE TITLE
NFT: restrict file access options.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#828]
Allocation changes to support NFTs.

1.  [x] Allocations cannot have the duration reduced. Change for all allocations.
4.  [x] Cannot be made mutable once set immutable.
3.  [x] Add an `anyone can extend` boolean flag.
5.  [x] Six new boolean options, `upload`,`delete`, `update`, `move`, `copy` and `rename`. These toggle whether the owner or anyone else can upload, delete, update, move, copy or rename files respectively.

This continues https://github.com/0chain/0chain/issues/538  Points (2) and (3) done in https://github.com/0chain/0chain/pull/620 https://github.com/0chain/gosdk/pull/288 and https://github.com/0chain/zboxcli/pull/122

Edit: Removed references to NFT, all CRUD operations default to true as below.

**Comment by guruhubb** [comment]
@Sriep, please make this generic that applies to any allocation. We don't need to use the `--nft` flag at all.  
The defaults can be `true` for all CRUDs, `mutable`, and `not everyone` can `extend` or `fund` an allocation.

**Comment by guruhubb** [comment]
@Sriep item 6 is not necessary. The default for any allocation is all CRUD operations are true.  For NFT, the client sets some of them as false if they want the NFT to be mutable but restricted. cc. @kushthedude

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by devyetii** [comment]
@lawRathod Why is this still open ?

**Comment by lawRathod** [comment]
@devyetii that's because https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L555-L557 was commented since it broke system tests. There's need to fix the system tests and revert the hotfix.

**Comment by devyetii** [comment]
@lawRathod Thanks for mentioning this. Also based on my investigation, I think also the validator of the request in blobber repo doesn't obey the rules entered by the user to the allocation so I think this also needs changes. As well as a check in "zboxcli" as FE to avoid unnecessary requests.

**Comment by devyetii** [comment]
This is to track my progress.

- [x] [0chain] An allocation once added, its expiry date cannot be reduced
- [x] [0chain] An allocation once added, cannot be mutable if it was immutable -> Already there
- [x] [0chain] [[0chain/0chain#1825](https://github.com/0chain/0chain/issues/1825)] An allocation cannot be updated (extended) by another user if the owner disables this feature
- [ ] [gosdk] [[0chain/gosdk#686](https://github.com/0chain/gosdk/issues/686)] related changes to allocation class and its workers
- [x] [blobber] [[0chain/blobber#476](https://github.com/0chain/blobber/issues/476)] Should validate requests against file CRUD options
- [ ] [zboxcli] Add flags on `newallocation` and `get` commands for the new fields with default values
- [ ] Fix system tests

**Comment by devyetii** [comment]
@guruhubb I've finished and pushed the changes to 0chain and blobber repos related to this issue. Now the changes pushed are meant to put these flags mentioned in the description of this issue in action. Still there's need to be able to add them by the owner of the allocation through zbox and gosdk. I'll be opening issues there to apply these changes. Is this OK ? cc @dabasov
